import React from 'react'
import Navbar from '../components/home/Navbar'

function page() {
  return (
    <div>
      <div className="bg-slate-950 h-[60vh] about-bg">
        <Navbar />
        <div className="h-full overflow-hidden text-center text-white flex items-center justify-center" data-aos="fade-up" data-aos-duration="3000">
          <h2 className="text-6xl font-semibold my-5">About Us</h2>
        </div>
      </div>


      <div className="container mx-auto">
        <div className='md:flex my-10 gap-5'>
          <div className="flex-1" data-aos="fade-right">
            <img src="/images/aboutus.jpg" alt="image" className="object-cover w-full h-full" />
          </div>
          <div className="flex-1  p-5 md:p-0" data-aos="fade-left" data-aos-duration="3000">
            <h3 className="text-3xl font-semibold my-5">Know More About us</h3>
            <p className="text-lg text-gray-600">As a multi-industry holding company based in Ghana, our investment scope,cut across Africa. GG44 Holdings Ltd, provide competitive advantage, drive sustainability and deliver trust. The solutions we provide reflect the insights generated by our diverse, global business platform, which encompasses private equity,Venture Capital , real estate funds, hedge fund solutions, credit funds and independent advisory and restructuring practices. </p>
            <br />
            <p className="text-lg text-gray-600">
              We have built the firm on a strong foundation of intellectual and financial capital. We focus on attracting exceptionally talented people and on creating an atmosphere that rewards initiative and independent thinking. Our solid financial base, including strong capital and liquidity which ensures our capacity to deliver on our commitments.
            </p>
            <br />
            <p className="text-lg text-gray-600">
              Above all, we have made it our No. 1 priority to serve the needs of our investors and clients. This commitment is reflected in a culture that values integrity, professionalism and a passion for excellence. It also leads us to operate with prudence, financial discipline, a long-term perspective, and a clear understanding that trust is something we must earn every day.
            </p>
          </div>
        </div>


        <div className="my-10" data-aos="fade-up" data-aos-duration="3000">
          <div>
            <div className="grid md:grid-cols-2">
              <div className="bg-slate-100 p-5">
                <h3 className="text-3xl font-semibold my-5">Our Mission</h3>
                <p className="text-gray-400 ">
                  To deliver investment solutions, unlock value and propel growth. Our capital programs, fuels the development of businesses and communities across Africa. Our strategy, is to help companies and governments stabilize, grow and thrive during challenging times. We invest in emerging markets and industries that will be the wellsprings of future opportunity.
                </p>
              </div>
              <div className="bg-slate-50 p-5">
                <h3 className="text-3xl font-semibold my-5">Our Vision</h3>
                <p className="text-gray-400 ">
                  To commit ourselves to the success of our company, by pursuing business excellence, the growth of our employees, and to seeking unique investments opportunities with good returns for our investors.
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>



    </div>
  )
}

export default page