import { Inter,Raleway,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/home/Navbar";
import Footer from "./components/Footer";
import { FaWhatsapp } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {/* <Navbar/> */}
        {children}
        <a href="https://wa.me/+233247685717" target="_blank" className="z-50">
          <div className="w-16 h-16 bg-green-600 fixed right-10 bottom-10 rounded-full flex justify-center items-center text-white shadow-lg "><FaWhatsapp size={30} /></div>
        </a>
        <Footer />
      </body>
    </html>
  );
}
