import { Inter,Poppins,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/home/Navbar";
import Footer from "./components/Footer";
import { FaWhatsapp } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <Navbar/> */}
        {children}
        {/*  */}
        <Footer />
      </body>
    </html>
  );
}
