import React from 'react'
import Link from 'next/link'

function Partners() {
  return (
    <div className="py-10">
      <div className="container mx-auto">
        <div className='md:flex'>
          <div className="flex-1" data-aos="fade-right">
            <img src="/images/aboutus.jpg" alt="image" className="object-cover w-full h-full" />
          </div>
          <div className="flex-1 md:px-10 p-3" data-aos="fade-left">
            <h3 className="text-6xl font-semibold my-5">About Us</h3>
            <p className=" text-gray-600">At GG44 Holdings, we apply our strengths as a leading investment and advisory firm to deliver
              solutions, unlock value and propel growth. Our capital programs, fuels the development of
              businesses and communities. Our strategic advice helps companies and governments stabilize,
              grow and thrive during these challenging times. We invest in emerging markets and entrepreneurs
              that will be the wellsprings of future opportunity.</p>
              <br />
            <p className=" text-gray-600">
              The solutions we provide reflect the insights generated by our diverse, global business platform,
              which encompasses private equity,Venture Capital , real estate funds, hedge fund solutions, credit
              funds and independent advisory and restructuring practices. We have built the firm on a strong
              foundation of intellectual and financial capital. We focus on attracting exceptionally talented people
              and on creating an atmosphere that rewards initiative and independent thinking. Our solid financial
              base, including strong capital and liquidity which ensures our capacity to deliver on our
              commitments. <br />

              <Link href="/about" className="text-blue-700">Read More</Link>
            </p>
            <br />
            
          </div>
        </div>
      </div>
    </div>
  )
}

export default Partners