import React from 'react'
import Link from 'next/link'

function Partners() {
  return (
    <div className="md:py-20 py-10 white-bg">
      <div className="container mx-auto">
        <div className='md:flex'>
          <div className="flex-1" data-aos="fade-right">
            <img src="/images/3.jpg" alt="image" className="object-cover w-full h-full" />
          </div>
          <div className="flex-1 md:px-10 p-3" data-aos="fade-left">
            <h3 className="text-3xl font-semibold my-5 text-gray-500">WHO IS GG44</h3>
            <p className=" text-gray-600 text-xl">GG44 Holdings Ltd, is a multi-industry holding company based in Ghana, we work directly with and on behalf of private companies seeking debt/equity/project financing from export credit agencies, grant providing agencies, private sources of capital and funds for purposes of privatization, restructuring or start-up capital for businesses in Africa. </p>
              <br />
            <p className=" text-gray-600 text-xl">
            The solutions we provide reflect the insights generated by our diverse, global business platform, which encompasses private equity funds,Venture Capital, real estate funds, hedge fund solutions, credit funds and independent advisory and restructuring practices. <br />

              <Link href="/about" className="text-blue-700">Read More</Link>
            </p>
            <br />
            
          </div>
        </div>
      </div>
    </div>
  )
}

export default Partners